// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6.Models;

namespace Mission6.Migrations
{
    [DbContext(typeof(MovieFormContext))]
    partial class MovieFormContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission6.Models.FormResponse", b =>
                {
                    b.Property<int>("FormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("FormId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            FormId = 1,
                            Category = "Comedy",
                            Director = "Anne Fletcher",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "The Proposal",
                            Year = 2009
                        },
                        new
                        {
                            FormId = 2,
                            Category = "Drama",
                            Director = "Anne Fletcher",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "27 Dresses",
                            Year = 2008
                        },
                        new
                        {
                            FormId = 3,
                            Category = "Comedy",
                            Director = "Nick Cassavetes",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "The Other Woman",
                            Year = 2014
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
